[package]
name = "pool"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
royalty="0x296e53ce1956ebdef5d969f3189a00b0ca29f2d377b311e30872202d4072b19b"
deployer = "0xabde8cd6f1218ae192b44a8786c8a276d0fb641cdd6e4dca11480cb6c924cfc0"
swap = "0xcb104808bc58d83c8d2773cc89f75db383268e4df391ee5ec14ec1ee7c164297"
[dev-addresses]



[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
