[package]
name = "pool"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
royalty="0x296e53ce1956ebdef5d969f3189a00b0ca29f2d377b311e30872202d4072b19b"
deployer ="0xa113c713c3c08b676970bfbe0be1ee9dfa70c1c15acc15f20daabf2c029f7f22"
swap = "0xad3648f9aadc54f0b159b02edd054bf6f2d72c5862fadd5035eadc0f834f670d"
[dev-addresses]


[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
